/* CREATE DATABASE 'fbgwtest1.fdb' PAGE_SIZE 8192 USER 'sysdba' PASSWORD 'masterkey' DEFAULT CHARACTER SET UTF8; */

CREATE DATABASE 'fbgwtest1.fdb' PAGE_SIZE 8192 DEFAULT CHARACTER SET UTF8;

/********************* ROLES **********************/

CREATE ROLE ADMINISTRATOR;
CREATE ROLE CASHIER;
CREATE ROLE CLEANER;
CREATE ROLE ENTRANCE;
CREATE ROLE KIOSK;
/* CREATE ROLE RDB$ADMIN; */
CREATE ROLE REPLDATA;
CREATE ROLE REPLMETA;
/********************* UDFS ***********************/

DECLARE EXTERNAL FUNCTION ADDDAY
Timestamp, Integer
RETURNS Timestamp
ENTRY_POINT 'addDay'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION ADDDAY2
Timestamp, Integer, Timestamp
RETURNS PARAMETER 3
ENTRY_POINT 'addDay2'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION ADDHOUR
Timestamp, Integer
RETURNS Timestamp
ENTRY_POINT 'addHour'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION ADDMILLISECOND
Timestamp, Integer
RETURNS Timestamp
ENTRY_POINT 'addMilliSecond'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION ADDMINUTE
Timestamp, Integer
RETURNS Timestamp
ENTRY_POINT 'addMinute'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION ADDMONTH
Timestamp, Integer
RETURNS Timestamp
ENTRY_POINT 'addMonth'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION ADDSECOND
Timestamp, Integer
RETURNS Timestamp
ENTRY_POINT 'addSecond'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION ADDWEEK
Timestamp, Integer
RETURNS Timestamp
ENTRY_POINT 'addWeek'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION ADDYEAR
Timestamp, Integer
RETURNS Timestamp
ENTRY_POINT 'addYear'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION DIV
Integer, Integer
RETURNS Double precision BY VALUE 
ENTRY_POINT 'IB_UDF_div'
MODULE_NAME 'ib_udf';

DECLARE EXTERNAL FUNCTION DOW
Timestamp, Varchar(60)
RETURNS PARAMETER 2
ENTRY_POINT 'DOW'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION DPOWER
Double precision BY DESCRIPTOR , Double precision BY DESCRIPTOR , Double precision BY DESCRIPTOR 
RETURNS PARAMETER 3
ENTRY_POINT 'power'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION FN_BLOBBINCMP
blob, blob
RETURNS Integer BY VALUE 
ENTRY_POINT 'BlobBinCmp'
MODULE_NAME 'FREEUDFLIB.DLL';

DECLARE EXTERNAL FUNCTION FN_CRLF

RETURNS CSTRING(3) CHARACTER SET NONE
ENTRY_POINT 'CRLF'
MODULE_NAME 'FreeUDFLib.dll';

DECLARE EXTERNAL FUNCTION FN_GETRANDOM
Integer NULL 
RETURNS Double precision BY VALUE 
ENTRY_POINT 'GetRandom'
MODULE_NAME 'RANDOMUDF.DLL';

DECLARE EXTERNAL FUNCTION FN_INITRANDOM

RETURNS Integer BY VALUE 
ENTRY_POINT 'InitRandom'
MODULE_NAME 'RANDOMUDF.DLL';

DECLARE EXTERNAL FUNCTION FN_LRTRIM
CSTRING(1020) NULL 
RETURNS CSTRING(1020)
ENTRY_POINT 'lrTrim'
MODULE_NAME 'FreeUDFLib';

DECLARE EXTERNAL FUNCTION FN_MD5SUM
CSTRING(1020) NULL , CSTRING(40) CHARACTER SET NONE
RETURNS PARAMETER 2
ENTRY_POINT 'MD5sum'
MODULE_NAME 'CRYPTUDF.DLL';

DECLARE EXTERNAL FUNCTION FN_RANDOMSTR
Integer, Integer, CSTRING(16000) CHARACTER SET NONE
RETURNS PARAMETER 3
ENTRY_POINT 'RandomStr'
MODULE_NAME 'RANDOMUDF.DLL';

DECLARE EXTERNAL FUNCTION FN_RANDOMSTRE
Integer, Integer, CSTRING(16000) CHARACTER SET NONE
RETURNS PARAMETER 3
ENTRY_POINT 'RandomStrE'
MODULE_NAME 'RANDOMUDF.DLL';

DECLARE EXTERNAL FUNCTION FN_SETRANDSEED
Integer NULL 
RETURNS Integer BY VALUE 
ENTRY_POINT 'SetRandSeed'
MODULE_NAME 'RANDOMUDF.DLL';

DECLARE EXTERNAL FUNCTION FN_SHA1SUM
CSTRING(1020) NULL , CSTRING(40) CHARACTER SET NONE
RETURNS PARAMETER 2
ENTRY_POINT 'SHA1sum'
MODULE_NAME 'CRYPTUDF.DLL';

DECLARE EXTERNAL FUNCTION I64ROUND
Numeric(18,4) BY DESCRIPTOR , Numeric(18,4) BY DESCRIPTOR 
RETURNS PARAMETER 2
ENTRY_POINT 'fbround'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION I64TRUNCATE
Numeric(18,0) BY DESCRIPTOR , Numeric(18,0) BY DESCRIPTOR 
RETURNS PARAMETER 2
ENTRY_POINT 'fbtruncate'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION ISLEAPYEAR
Timestamp
RETURNS Integer BY VALUE 
ENTRY_POINT 'isLeapYear'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION LTRIM
CSTRING(1020) NULL 
RETURNS CSTRING(1020)
ENTRY_POINT 'IB_UDF_ltrim'
MODULE_NAME 'ib_udf';

DECLARE EXTERNAL FUNCTION ROUND
Integer BY DESCRIPTOR , Integer BY DESCRIPTOR 
RETURNS PARAMETER 2
ENTRY_POINT 'fbround'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION RTRIM
CSTRING(1020) NULL 
RETURNS CSTRING(1020)
ENTRY_POINT 'IB_UDF_rtrim'
MODULE_NAME 'ib_udf';

DECLARE EXTERNAL FUNCTION SDOW
Timestamp, Varchar(20)
RETURNS PARAMETER 2
ENTRY_POINT 'SDOW'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION SRAND

RETURNS Double precision BY VALUE 
ENTRY_POINT 'IB_UDF_srand'
MODULE_NAME 'ib_udf';

DECLARE EXTERNAL FUNCTION SRIGHT
Varchar(400) BY DESCRIPTOR , Smallint, Varchar(400) BY DESCRIPTOR 
RETURNS PARAMETER 3
ENTRY_POINT 'right'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION STRING2BLOB
Varchar(1200) BY DESCRIPTOR , blob
RETURNS PARAMETER 2
ENTRY_POINT 'string2blob'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION STRLEN
CSTRING(32767) CHARACTER SET NONE
RETURNS Integer BY VALUE 
ENTRY_POINT 'IB_UDF_strlen'
MODULE_NAME 'ib_udf';

DECLARE EXTERNAL FUNCTION SUBSTR
CSTRING(1020) NULL , Smallint, Smallint
RETURNS CSTRING(1020)
ENTRY_POINT 'IB_UDF_substr'
MODULE_NAME 'ib_udf';

DECLARE EXTERNAL FUNCTION SUBSTRLEN
CSTRING(1020) NULL , Smallint, Smallint
RETURNS CSTRING(1020)
ENTRY_POINT 'IB_UDF_substrlen'
MODULE_NAME 'ib_udf';

DECLARE EXTERNAL FUNCTION TRUNCATE
Integer BY DESCRIPTOR , Integer BY DESCRIPTOR 
RETURNS PARAMETER 2
ENTRY_POINT 'fbtruncate'
MODULE_NAME 'fbudf';

DECLARE EXTERNAL FUNCTION UDF_FRAC
Double precision
RETURNS Double precision BY VALUE 
ENTRY_POINT 'IB_UDF_frac'
MODULE_NAME 'ib_udf';

/****************** GENERATORS ********************/

/******************** DOMAINS *********************/

/******************* PROCEDURES ******************/

/******************** TABLES **********************/

/********************* VIEWS **********************/

/******************* EXCEPTIONS *******************/

/******************** TRIGGERS ********************/


