/* This file defines the misc udfs for Firebird. */

set sql dialect 3;

DECLARE EXTERNAL FUNCTION FN_BLOBBINCMP
blob, blob
RETURNS Integer BY VALUE 
ENTRY_POINT 'BlobBinCmp'
MODULE_NAME 'FREEUDFLIB.DLL';

DECLARE EXTERNAL FUNCTION FN_CRLF

RETURNS CSTRING(3) CHARACTER SET NONE
ENTRY_POINT 'CRLF'
MODULE_NAME 'FreeUDFLib.dll';

DECLARE EXTERNAL FUNCTION FN_GETRANDOM
Integer NULL 
RETURNS Double precision BY VALUE 
ENTRY_POINT 'GetRandom'
MODULE_NAME 'RANDOMUDF.DLL';

DECLARE EXTERNAL FUNCTION FN_INITRANDOM

RETURNS Integer BY VALUE 
ENTRY_POINT 'InitRandom'
MODULE_NAME 'RANDOMUDF.DLL';

DECLARE EXTERNAL FUNCTION FN_LRTRIM
CSTRING(1020) NULL 
RETURNS CSTRING(1020)
ENTRY_POINT 'lrTrim'
MODULE_NAME 'FreeUDFLib';

DECLARE EXTERNAL FUNCTION FN_MD5SUM
CSTRING(1020) NULL , CSTRING(40) CHARACTER SET NONE
RETURNS PARAMETER 2
ENTRY_POINT 'MD5sum'
MODULE_NAME 'CRYPTUDF.DLL';

DECLARE EXTERNAL FUNCTION FN_RANDOMSTR
Integer, Integer, CSTRING(16000) CHARACTER SET NONE
RETURNS PARAMETER 3
ENTRY_POINT 'RandomStr'
MODULE_NAME 'RANDOMUDF.DLL';

DECLARE EXTERNAL FUNCTION FN_RANDOMSTRE
Integer, Integer, CSTRING(16000) CHARACTER SET NONE
RETURNS PARAMETER 3
ENTRY_POINT 'RandomStrE'
MODULE_NAME 'RANDOMUDF.DLL';

DECLARE EXTERNAL FUNCTION FN_SETRANDSEED
Integer NULL 
RETURNS Integer BY VALUE 
ENTRY_POINT 'SetRandSeed'
MODULE_NAME 'RANDOMUDF.DLL';

DECLARE EXTERNAL FUNCTION FN_SHA1SUM
CSTRING(1020) NULL , CSTRING(40) CHARACTER SET NONE
RETURNS PARAMETER 2
ENTRY_POINT 'SHA1sum'
MODULE_NAME 'CRYPTUDF.DLL';
